base_images:
  cli:
    name: "4.12"
    namespace: ocp
    tag: cli
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.12"
  tests-private-ui:
    name: tests-private-ui
    namespace: ci
    tag: "4.12"
  tools:
    name: "4.12"
    namespace: ocp
    tag: tools
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.12"
resources:
  '*':
    requests:
      cpu: 200m
      memory: 400Mi
tests:
- as: aws-ipi-proxy-fips-f60
  cron: 43 3 13 1,3,5,7,9,11 *
  steps:
    cluster_profile: aws-quay-qe
    env:
      BASE_DOMAIN: quayqe.devcluster.openshift.com
      CATALOG_SOURCE_NAME: compliance-operator
      FILTERS_ADDITIONAL: ""
      FIPS_ENABLED: "true"
      OO_BUNDLE: quay.io/redhat-user-workloads/ocp-isc-tenant/compliance-operator-bundle-release:release-1.7
      OO_INSTALL_NAMESPACE: openshift-compliance
      TEST_FILTERS: ~HyperShiftMGMT&;~DEPRECATED&
      TEST_PARALLEL: "3"
      TEST_SCENARIOS: Compliance_Operator
      TEST_TIMEOUT: "30"
      TEST_TYPE: release
    test:
    - ref: file-integrity-konflux-catalogsource
    - ref: optional-operators-operator-sdk-non-ci-bundle-image
    - ref: openshift-extended-test
    - ref: openshift-e2e-test-qe-report
    workflow: cucushift-installer-rehearse-aws-ipi-proxy
zz_generated_metadata:
  branch: master
  org: ComplianceAsCode
  repo: ocp4e2e
  variant: nightly-4.12
