base_images:
  cli:
    name: "4.19"
    namespace: ocp
    tag: cli
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.19"
  tests-private-ui:
    name: tests-private-ui
    namespace: ci
    tag: "4.19"
  tools:
    name: "4.19"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.19"
    namespace: ocp
    tag: upi-installer
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.19"
resources:
  '*':
    requests:
      cpu: 200m
      memory: 400Mi
tests:
- as: baremetalds-ipi-ovn-lvms-f7
  cluster: build05
  cron: 23 3 2,9,16,23 * *
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      CATALOG_SOURCE_NAME: compliance-operator
      E2E_RUN_TAGS: '@complianceoperator'
      FILTERS_ADDITIONAL: ""
      LVM_OPERATOR_SUB_CHANNEL: stable-4.19
      LVM_OPERATOR_SUB_SOURCE: qe-app-registry
      OO_BUNDLE: quay.io/redhat-user-workloads/ocp-isc-tenant/compliance-operator-bundle-release:release-1.7
      OO_INSTALL_NAMESPACE: openshift-compliance
      TEST_FILTERS: ~HyperShiftMGMT&;~DEPRECATED&
      TEST_PARALLEL: "3"
      TEST_SCENARIOS: Compliance_Operator
      TEST_TIMEOUT: "30"
      TEST_TYPE: release
    test:
    - ref: file-integrity-konflux-catalogsource
    - ref: optional-operators-operator-sdk-non-ci-bundle-image
    - ref: openshift-extended-test
    - ref: openshift-extended-web-tests
    - ref: openshift-e2e-test-qe-report
    workflow: cucushift-installer-rehearse-baremetalds-ipi-ovn-lvms
zz_generated_metadata:
  branch: master
  org: ComplianceAsCode
  repo: ocp4e2e
  variant: nightly-4.19
