base_images:
  cli:
    name: "4.16"
    namespace: ocp
    tag: cli
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.16"
  tests-private-ui:
    name: tests-private-ui
    namespace: ci
    tag: "4.16"
  tools:
    name: "4.16"
    namespace: ocp
    tag: tools
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.16"
resources:
  '*':
    requests:
      cpu: 200m
      memory: 400Mi
tests:
- as: ibmcloud-ipi-private-fips-f60
  cron: 35 12 14 2,4,6,8,10,12 *
  steps:
    cluster_profile: ibmcloud-qe
    env:
      CATALOG_SOURCE_NAME: compliance-operator
      E2E_RUN_TAGS: '@complianceoperator'
      FILTERS_ADDITIONAL: ""
      FIPS_ENABLED: "true"
      OO_BUNDLE: quay.io/redhat-user-workloads/ocp-isc-tenant/compliance-operator-bundle-release:release-1.7
      OO_INSTALL_NAMESPACE: openshift-compliance
      TEST_FILTERS: ~HyperShiftMGMT&;~DEPRECATED&
      TEST_PARALLEL: "3"
      TEST_SCENARIOS: Compliance_Operator
      TEST_TIMEOUT: "30"
      TEST_TYPE: release
    test:
    - ref: file-integrity-konflux-catalogsource
    - ref: optional-operators-operator-sdk-non-ci-bundle-image
    - ref: openshift-extended-test
    - ref: openshift-extended-web-tests
    - ref: openshift-e2e-test-qe-report
    workflow: cucushift-installer-rehearse-ibmcloud-ipi-private
zz_generated_metadata:
  branch: master
  org: ComplianceAsCode
  repo: ocp4e2e
  variant: nightly-4.16
